alias open='xdg-open'
alias wget='wget --no-hsts'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -l --color=auto --group-directories-first'
alias la='ls -l --color=auto --group-directories-first'